package provider

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-go/tfprotov6"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
)

// stringMapProtocolValue returns the raw element map that
// organizationProjectProtocolValue wraps in the attribute's map type.
func stringMapProtocolValue(values map[string]string) map[string]tftypes.Value {
	elements := make(map[string]tftypes.Value, len(values))
	for key, value := range values {
		elements[key] = tftypes.NewValue(tftypes.String, value)
	}
	return elements
}

func TestIsLiteLLMModelInfoPricingKey(t *testing.T) {
	for _, key := range []string{
		"input_cost_per_token", "output_cost_per_token", "cache_read_input_token_cost",
		"input_cost_per_second", "output_cost_per_pixel", "tiered_pricing",
		"input_cost_per_token_above_200k_tokens", "regional_processing_uplift_multiplier_eu",
		// Undeclared tiered rates are still pricing to LiteLLM.
		"custom_rate_above_64k_tokens", "custom_rate_above_1000_tokens",
		// Generated by /model/info; "key" marks a copied response.
		"key", "pricing_overrides",
	} {
		if !isLiteLLMModelInfoPricingKey(key) {
			t.Errorf("%q must be treated as pricing", key)
		}
	}
	for _, key := range []string{
		"supports_vision", "supports_function_calling", "max_tokens", "max_input_tokens",
		// Explicitly exempt upstream: it describes the embedding, not a price.
		"output_vector_size",
		"key_alias", "pricing_note", "above_200k_tokens_note",
	} {
		if isLiteLLMModelInfoPricingKey(key) {
			t.Errorf("%q must not be treated as pricing", key)
		}
	}
}

// TestModelPricingKeysMatchPinnedContract derives LiteLLM's pricing field set
// from the pinned OpenAPI LiteLLM_Params schema. At v1.104.0 every pricing
// field, and no other parameter, contains "cost" or "pricing" or is a regional
// uplift multiplier. A re-pin that adds, renames, or removes a pricing field
// fails here until liteLLMModelPricingKeys is reviewed.
func TestModelPricingKeysMatchPinnedContract(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("..", "..", "openapi.json"))
	if err != nil {
		t.Fatal(err)
	}
	var document struct {
		Components struct {
			Schemas map[string]struct {
				Properties map[string]json.RawMessage `json:"properties"`
			} `json:"schemas"`
		} `json:"components"`
	}
	if err := json.Unmarshal(raw, &document); err != nil {
		t.Fatal(err)
	}
	params, ok := document.Components.Schemas["LiteLLM_Params"]
	if !ok || len(params.Properties) == 0 {
		t.Fatal("pinned OpenAPI has no LiteLLM_Params properties")
	}
	var derived []string
	for name := range params.Properties {
		if strings.Contains(name, "cost") || strings.Contains(name, "pricing") || strings.Contains(name, "_uplift_multiplier") {
			derived = append(derived, name)
		}
	}
	sort.Strings(derived)
	pinned := sortedKeys(liteLLMModelPricingKeys)
	if strings.Join(derived, "\n") != strings.Join(pinned, "\n") {
		t.Fatalf("pricing keys drifted from the pinned contract\nderived (%d): %v\nprovider (%d): %v", len(derived), derived, len(pinned), pinned)
	}
}

func TestModelInfoPricingKeysRejectedAtValidation(t *testing.T) {
	ctx := context.Background()
	protocolServer, schemas := configuredImportProtocolServer(t, ctx, "http://127.0.0.1:1")
	schema := schemas.ResourceSchemas["litellm_model"]
	base := map[string]interface{}{"model_name": "priced", "custom_llm_provider": "openai", "base_model": "gpt-4o-mini"}
	with := func(extra map[string]interface{}) *tfprotov6.DynamicValue {
		values := map[string]interface{}{}
		for key, value := range base {
			values[key] = value
		}
		for key, value := range extra {
			values[key] = value
		}
		return accessGroupProtocolDynamicValue(t, schema, organizationProjectProtocolValue(t, schema, values))
	}
	for _, test := range []struct {
		name      string
		extra     map[string]interface{}
		wantError bool
	}{
		{"map pricing key", map[string]interface{}{"additional_model_info": stringMapProtocolValue(map[string]string{"input_cost_per_token": "0.000003"})}, true},
		{"map tiered pricing key", map[string]interface{}{"additional_model_info": stringMapProtocolValue(map[string]string{"input_cost_per_token_above_200k_tokens": "0.000006"})}, true},
		{"map generated key", map[string]interface{}{"additional_model_info": stringMapProtocolValue(map[string]string{"key": "gpt-4o-mini"})}, true},
		{"map capability flag", map[string]interface{}{"additional_model_info": stringMapProtocolValue(map[string]string{"supports_vision": "true"})}, false},
		{"json pricing key", map[string]interface{}{"additional_model_info_json": `{"cache_read_input_token_cost":5e-7}`}, true},
		{"json capability flag", map[string]interface{}{"additional_model_info_json": `{"supports_reasoning":true}`}, false},
		{"pricing in litellm params", map[string]interface{}{"additional_litellm_params": stringMapProtocolValue(map[string]string{"cache_read_input_token_cost": "0.0000005"})}, false},
	} {
		t.Run(test.name, func(t *testing.T) {
			response, err := protocolServer.ValidateResourceConfig(ctx, &tfprotov6.ValidateResourceConfigRequest{TypeName: "litellm_model", Config: with(test.extra)})
			if err != nil {
				t.Fatal(err)
			}
			text := agentProtocolDiagnosticsText(response.Diagnostics)
			if accessGroupProtocolDiagnosticsHaveError(response.Diagnostics) != test.wantError {
				t.Fatalf("diagnostics=%s", text)
			}
			if test.wantError && (!strings.Contains(text, "Custom Pricing Is Not Supported in Model Information") || !strings.Contains(text, "additional_litellm_params")) {
				t.Fatalf("diagnostic lacks guidance: %s", text)
			}
			if strings.Contains(text, "0.000003") || strings.Contains(text, "5e-7") {
				t.Fatalf("diagnostic leaked a configured value: %s", text)
			}
		})
	}
}
